:bike:

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -15,11 +15,11 @@ jobs:
     - run: |
         if [ -z ${{ github.event.inputs.count }} ]
         then
-          echo "${{ github.event.inputs.count }} is NULL"
+          echo "${{ github.event.inputs.count }} is NULL, continuing with count calculations"
         else
           echo "${{ github.event.inputs.count }} is NOT NULL"
-        fi
-        if ! [[ ${{ github.event.inputs.count }} =~ '^[0-9]+$' ]]; then
-          echo "error: Not a number" >&2; exit 1
+          if ! [[ ${{ github.event.inputs.count }} =~ '^[0-9]+$' ]]; then
+            echo "error: Not a number" >&2; exit 1
+          fi
         fi
 
