:bike:

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -18,8 +18,9 @@ jobs:
           echo "${{ github.event.inputs.count }} is NULL, continuing with count calculations"
         else
           echo "${{ github.event.inputs.count }} is NOT NULL"
-          if ! [[ ${{ github.event.inputs.count }} =~ '^[0-9]+$' ]]; then
-            echo "error: Not a number" >&2; exit 1
+          if [[ ${{ github.event.inputs.count }} =~ '^[0-9]+$' ]]; then
+            echo " ${{ github.event.inputs.count }} looks like a number"
+          else
+            echo "error: ${{ github.event.inputs.count }} is not a number" >&2; exit 1
           fi
         fi
-
