:bike:

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -17,9 +17,10 @@ jobs:
           echo "info: ${{ github.event.inputs.count }} is NULL, continuing with count calculations"
         else
           echo "info: ${{ github.event.inputs.count }} is NOT NULL"
-          if [[ ${{ github.event.inputs.count }} =~ '^[0-9]+$' ]]; then
+          if [[ '${{ github.event.inputs.count }}' =~ '^[0-9]+$' ]]; then
             echo "info: ${{ github.event.inputs.count }} is a number"
           else
-            echo "error: ${{ github.event.inputs.count }} is NOT a number" >&2; exit 1
+            echo "error: ${{ github.event.inputs.count }} is NOT a number"
+            exit 1
           fi
         fi
